require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude: ['bin/life_game']

Naming/MethodName:
  AllowedPatterns: [Rainbow]

Layout/ArgumentAlignment: 
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
